### ISSUE TITLE
To use other fields than just one which is indicated with "measure"  in "formula" to specify more complex conditions 

### ISSUE THREAD

**Issue by HusnuAkcak** [WebDataRocks/web-pivot-table#1]
```
"conditions": [	
    {
        "formula": "#value < 8",
        "measure": "time_info",
        "format": {
            "backgroundColor": "#FFFFFF"
        }
    }
]
```

I can use #value as a comparison argument but I need to express a more complex condition, how to reach other fields of the record?

**Comment by se7enteenblue** [comment]
Hello!

Thank you for posting your question.

We think you will find the following CodePen sample helpful: https://codepen.io/webdatarocks/pen/LYLZgoM
On 7th line we use the field’s name to refer to another field’s value in the condition. For example, "'Price' > 10000".

Please let us know if this helps.

Kind regards,
Nadia
