### ISSUE TITLE
how to bind JSON data from ajax call to DataSource of pivot table webdatarocks. Here the data is not binding in the following code. Please help me

### ISSUE THREAD

**Issue by maithamaraju** [WebDataRocks/web-pivot-table#10]
var pivot = new WebDataRocks({
                container: "#wdr-component",
                toolbar: true,
                height: 395,
                report: {
                    dataSource: {
                        dataSourceType: "json",
                        data: **getData()**
                    },
                    "slice": {
                        "rows": [
                            {
                                "uniqueName": "RLI_RAV_GRP_DES"
                            }
                        ],
                        "columns": [
                            {
                                "uniqueName": "LEVEL1"
                            },
                            {
                                "uniqueName": "LEVEL2"
                            }
                        ],
                        "measures": [
                            {
                                "uniqueName": "Q1",
                                "aggregation": "sum"
                            },
                            {
                                "uniqueName": "Q2",
                                "aggregation": "sum"
                            },
                            {
                                "uniqueName": "Q3",
                                "aggregation": "sum"
                            },
                            {
                                "uniqueName": "Q4",
                                "aggregation": "sum"
                            }
                        ]
                    },
                    options:
                    {
                        grid: {
                            title: "Sales Report"
                        }
                    }
                }
            });

        

        function getData() {
            $.ajax({
                type: "GET",
                url: "NACGSample.aspx/GetPivotReportList",
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                success: function (msg) {
                    return JSON.parse(msg.d);
                    //return msg.d; 
                },
                error: function (msg) { return alert(msg); }
            });
        }
[Function JSON DATA.txt](https://github.com/WebDataRocks/web-pivot-table/files/7492770/Function.JSON.DATA.txt)

**Comment by se7enteenblue** [comment]
The issue is that you can not return a value from an asynchronous call (AJAX request). 
The solution is to call a function inside your `success:` callback that passes the data when it is available.

Please check the following CodePen: https://codepen.io/webdatarocks/pen/eYErgGL?editors=1010
