### ISSUE TITLE
Sorting by date bug ( desc or asc ) in Web-datarocks pivot tables

### ISSUE THREAD

**Issue by balaji319** [WebDataRocks/web-pivot-table#11]
Looks like there bug is the sorting the data ( Date type ) in web-data-rock table with sort: "desc" or "asc" 
 
 Please find code-pen with above issue : 
 
 https://codepen.io/BALAJIVP/pen/WNZJBjO
 
 
 Thank you 
![screenshot-nimbus-capture-2022 01 05-00_22_03](https://user-images.githubusercontent.com/20475558/148109125-da1fa0d2-4ef0-469a-bda3-23264ef4480b.png)

**Comment by maksymkaD** [comment]
Hi!

Thank you for writing to us.

We have checked the date sorting on our side, and it looks like sorting works correctly. Here you can see an example: https://codepen.io/maksymkad/pen/zYEaZzw. 
Firstly, we added the "measure" object, which specifies the measures to be selected to the slice. And secondly, we used the identifier of hierarchy as a value of the uniqueName property (for instance, uniqueName: "DayDate"). 
Also, we recommend configuring the slice via UI and saving your configuration with the Save tab from the Toolbar, which will download a JSON file with the report. This way of configuring slice may be more comfortable than doing it directly in code.

I hope my answer has helped you. 

Best Regards,
Max

**Comment by balaji319** [comment]
looks like approach needs to be modified 

appreciate your response :+1: 

thank you @maksymkaD
