### ISSUE TITLE
TS2503: Cannot find namespace 'WebDataRocks'.

### ISSUE THREAD

**Issue by willfjr** [WebDataRocks/web-pivot-table#13]
I have a react application and I'm trying to use WebDataRocks to render data from my bd. But, when I try to build I'm getting an error that says:

...node_modules/react-webdatarocks/build/index.d.ts(3,48):

TS2503: Cannot find namespace 'WebDataRocks'.

I tried many stuff, but I still receive the error. The only thing that's working is when I add a flag of ignoring the typescript type of and index.d.js. But, I can't change the modules because it's not gonna work when I send the code for prod area.

My guess is the file should be .tsx, not ts. But, again I can't change the modules.

Any thoughts?

**Comment by maksymkaD** [comment]
Hello!
Thank you for reaching out to us.
Please see this example from WebDataRocks. It contains a working React+TS project, and it may help you to solve the issue:
https://github.com/WebDataRocks/pivot-react/tree/master/typescript
