### ISSUE TITLE
Internal error when filtering by column values

### ISSUE THREAD

**Issue by adalweiss** [WebDataRocks/web-pivot-table#16]
When selecting a column on the chart there an option to choose which values display. However these changes produce an error and then have no effect. This happens whether or not slice is defined.

![1651076458](https://user-images.githubusercontent.com/86334532/165565871-aa086717-d69f-439d-b7e5-962f15203891.png)

**Comment by solja484** [comment]
Could you please specify the following details:
- What charting library do you use?
- Do you have calculated values in your report?

Also, it will be easier to understand the matter if you give the CodePen sample with this error reproducible.
