### ISSUE TITLE
missing column header in pdf

### ISSUE THREAD

**Issue by Kamo1966** [WebDataRocks/web-pivot-table#18]
In export pdf only the second pages of pdf is missing the headers. You can see the example attached.

![first_page](https://user-images.githubusercontent.com/98221105/201308359-75614566-0ba1-4fda-8834-a4b1410aca10.png)
![second_page](https://user-images.githubusercontent.com/98221105/201308348-7a98945d-9e1b-40fb-b86b-55add9d8ddba.png)
![third_page](https://user-images.githubusercontent.com/98221105/201308364-f06b6725-33a9-4e20-9e37-72b6cf2e44eb.png)
![last_page](https://user-images.githubusercontent.com/98221105/201308362-0d3aaeae-f644-4620-855d-ab720d2df2b8.png)

When you generate a 4 pages pdf (2 horizontal and 2 vertical) in PDF you will find 5 pages (one pages is a duplicate)

**Comment by maksymkaD** [comment]
Hello, @Kamo1966,

Thank you for reporting this issue. We will add this task to the backlog and provide a fix in one of our future releases.

Kind regards,
Max
