### ISSUE TITLE
'WebdatarocksPivotModule' does not appear to be an NgModule class

### ISSUE THREAD

**Issue by riad9808** [WebDataRocks/web-pivot-table#21]
hi 
i'm getting 'WebdatarocksPivotModule' does not appear to be an NgModule class when importing WebdatarocksPivotModule to the appmodule in angular , already installed ng-webdatarocks

`import { NgModule, isDevMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ServiceWorkerModule } from '@angular/service-worker';
import {  HttpClientModule } from '@angular/common/http';
import { AuthRoutingModule } from './auth-routing.module';
import { WebdatarocksPivotModule } from 'ng-webdatarocks';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    
    HttpClientModule,
    BrowserModule,
    WebdatarocksPivotModule,
    AppRoutingModule,
    AuthRoutingModule
    
    
  ],
  providers: [
    
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by maksymkaD** [comment]
Hello,

Could you please tell which versions of WebDataRocks and Angular are used in your project?
