### ISSUE TITLE
WebDataRocks(~1.3.3) grid\table not working properly on latest updated browsers 

### ISSUE THREAD

**Issue by gangamaism** [WebDataRocks/web-pivot-table#22]
We are using WebDataRocks version 1.3.3 (with angular 10.0 and Node 16.2) It was working fine till mid of Dec-2023. But as browser version updated since then getting issues in Chrome, Edge and Firefox latest versions.(It works fine if we downgrade the Chrome to 119.0.x.x)

Issue : First column first rows Cell displays on whole grid size (please find below attached screenshot for more details)

<img width="623" alt="Issues on latest browser" src="https://github.com/WebDataRocks/web-pivot-table/assets/127426820/538f14b1-3bca-4e0c-8a72-d6b8eef81524">

It works fine on Chrome 119.0.x.x(please find below screenshot)
<img width="650" alt="Works fine on old browser" src="https://github.com/WebDataRocks/web-pivot-table/assets/127426820/1feb1fa4-2024-4d44-946c-b36599c2739a">

**Comment by se7enteenblue** [comment]
Hello,

Thank you for reaching out to us.

We could not reproduce the issue on our side. Could you please check if there are any errors or messages in the browser developer console? This information would greatly help us to continue the investigation. Also, you can check if your custom CSS overrides WebDataRocks styles. 

Kind regards,
Nadia
