### ISSUE TITLE
Can't hide columns when there are ReportFilters(flat form)

### ISSUE THREAD

**Issue by jabbad-92** [WebDataRocks/web-pivot-table#23]
Steps to reproduce the issue:

1º Enter the link:
https://jsfiddle.net/6nL2xeat/

2º Change layout to "Flat form"

3º Go to Fields, uncheck column "Destination"

As you can see, the Destination column does not disappear but moves to the last position

**Comment by se7enteenblue** [comment]
Hello,

Thank you for reporting the described behavior.

We have added the issue to our backlog. Our team will consider a fix in our upcoming releases.

Kind regards,
Nadia
