### ISSUE TITLE
Empty table if only one row of data

### ISSUE THREAD

**Issue by ssaidnabiev** [WebDataRocks/web-pivot-table#24]
![image](https://github.com/WebDataRocks/web-pivot-table/assets/36405073/56af785c-d1c2-42dd-8523-557d1793df14)

Above is the data that is given to WebDataRocks. There are two rows, the first is the name of headers (firstObject), the second is the only row with data.
This issue is persistent, doesn't depend on browser or browser version.

Everything will show up if I add one more row of data, making total of 2 data rows.

**Comment by maksymkaD** [comment]
Hello,

Thank you for bringing this matter to our attention. 
We have added this issue to our backlog, a solution will be incorporated in upcoming updates.

Kind regards,
Maksym
