### ISSUE TITLE
getData() returns duplicate rows if 'Do Not Show Grand Totals' is selected

### ISSUE THREAD

**Issue by ElementumIT** [WebDataRocks/web-pivot-table#25]
I think this codePen shows the issue.  Maybe this is expected behavior, but thought I'd report it in case it's not.

https://codepen.io/Brett-Olges/pen/ZENQWNY

getData() returns the data from the pivot table, but if "Do Not Show Grand Totals" is selected as an option, then it seems like the data returns 2 sets of data, one of which is a duplicate?

**Comment by maksymkaD** [comment]
Hello, 

Thank you for reporting this issue.
We have included this in our backlog. The fix will be available in future updates.

Best regards,
Maksym
