### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by UnrulyMalonzy** [WebDataRocks/web-pivot-table#26]
I can't seem to find my To Local CSV

**Comment by se7enteenblue** [comment]
Hello,

Thank you for contacting us.

Kindly note that **To local CSV** tab is located in the **Connect** tab on the Toolbar. To enable the Toolbar, please use the following code:
```
let pivot = new WebDataRocks({
    container: "#wdr-component",
    toolbar: true
});
```
Don't forget to include into the project the following script:
`<script src="https://cdn.webdatarocks.com/latest/webdatarocks.toolbar.min.js"></script>`
If there is no Connect tab on the Toolbar, please check if there is any Toolbar customization in your project(e.g., beforetoolbarcreated event). You are welcome to check more details on connecting to the CSV file in our documentation: https://www.webdatarocks.com/doc/csv-data-source/

We hope that our response has addressed your question.

Kind regards,
Nadia

**Comment by se7enteenblue** [comment]
Hello,

Also, connecting to the local CSV is only supported for desktop devices. As a workaround, you can request the desktop site in the browser settings. This way, the Connect tab on the Toolbar will be available on mobile devices. 

We hope it helps.

Kind regards,
Nadia
