### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by Cyndy111** [WebDataRocks/web-pivot-table#27]
![image](https://github.com/WebDataRocks/web-pivot-table/assets/172160868/7b1709c1-b5be-4f26-8cb8-05cbc97e0db1)
How do I find the connect and local csv on the toolbar

**Comment by se7enteenblue** [comment]
Hello,

Please note that connecting to the local CSV is only supported for desktop devices. As a workaround, you can request the desktop site in the browser settings. This way, the Connect tab on the Toolbar will be available on mobile devices.

We hope it helps.

Kind regards,
Nadia
