### ISSUE TITLE
Distinct count shows 0 if date mapping is present

### ISSUE THREAD

**Issue by andilem** [WebDataRocks/web-pivot-table#28]
It seems that the "Distinct Count" aggregation only works for values without a space character. As soon as a value contains a space, the aggregation result always seems to be 0.

**Comment by se7enteenblue** [comment]
Hello,

Thank you for reaching out to us.

We could not reproduce the described behavior. Please modify the following example to show us the issue: https://codepen.io/webdatarocks/pen/qBGpgXL

Looking forward to hearing from you.

Kind regards,
Nadia

**Comment by andilem** [comment]
I'm sorry, it was not caused by the blank character, but by a year/month/day mapping which causes the bug.
Here is a reproducing example: https://codepen.io/alemmer/pen/WNBMwQr

**Comment by se7enteenblue** [comment]
Hello,

Thank you for the response.

We have added this to our backlog, and our team will provide a fix in future releases.

Kind regards,
Nadia
