### ISSUE TITLE
Math operations

### ISSUE THREAD

**Issue by Frominor** [WebDataRocks/web-pivot-table#29]
Hello!When working with your library on my website, I came across such a problem - when dividing a number by 0, the result of a mathematical calculation is the number 0.00011, which is not correct. What is it about and can you fix it?

**Comment by solja484** [comment]
Hi, Frominor!

Please note that when dividing by zero in WebDataRocks, the component shows `infinity` value by default.
Here is the example for reference: https://codepen.io/webdatarocks/pen/rNgKdpp.
Hope it helps. 

Kind regards,
Solomiia
