### ISSUE TITLE
Export to Excel. Header not added to Exported file

### ISSUE THREAD

**Issue by JakubWozniakStack** [WebDataRocks/web-pivot-table#32]
Hello,

I have encountered an issue where headers and footers are not added when exporting data to Excel.

Example
You can see a live demonstration of the issue in this [CodePen example](https://codepen.io/Jakub-Wozniak-the-bashful/pen/jOjLNeM).

**Steps to Reproduce**

1. Open the provided CodePen link.
2. Export the displayed data to Excel. (Works correct with PDF)
3. Notice that the exported Excel file lacks the specified headers and footers.

**Expected Behavior**
The exported Excel file should include the designated headers and footers as specified in the export settings.

Any guidance or suggestions on how to resolve this issue would be greatly appreciated. Thank you for your assistance!

**Comment by se7enteenblue** [comment]
Hello,

Thank you for reaching out to us.

Kindly note that adding headers and footers is only available for PDF and HTML export.

We hope that our response is helpful.

Kind regards,
Nadia
