### ISSUE TITLE
I am adding a new column to calculate a value. However, when I add two fields and try to swap them, an error occurs.

### ISSUE THREAD

**Issue by reliable-jitendra** [WebDataRocks/web-pivot-table#33]
https://github.com/user-attachments/assets/28e238fd-0514-4db3-891f-b01a1862a7a5

Uploading webrock - Made with Clipchamp.mp4…

**Comment by se7enteenblue** [comment]
Hello,

Thank you for reaching out to us.

We have added this to our backlog, and our team will provide a fix in future releases.

Kind regards,
Nadia
