### ISSUE TITLE
Column keeps expanding in small screen ration

### ISSUE THREAD

**Issue by parthsunilmodi** [WebDataRocks/web-pivot-table#5]
![Screenshot from 2021-03-02 14-54-54](https://user-images.githubusercontent.com/65945506/109627093-44bcbd80-7b67-11eb-90c5-ea3a206fdf3b.png)
![Screenshot from 2021-03-02 14-54-41](https://user-images.githubusercontent.com/65945506/109627097-45edea80-7b67-11eb-9421-61f31b3c5a0a.png)

**Comment by parthsunilmodi** [comment]
![Untitled_ Mar 2, 2021 2_43 PM](https://user-images.githubusercontent.com/65945506/109627778-fa880c00-7b67-11eb-9f55-d2113ef34e20.gif)

**Comment by mhalaida** [comment]
Thank you for reporting this behavior. This is a known issue that has already been added to our backlog. We'll consider a fix in our upcoming releases.
