### ISSUE TITLE
SaveToBinary callback

### ISSUE THREAD

**Issue by Clancey** [WebDataRocks/web-pivot-table#6]
Hello, I love your pivot table!
I am embedding it in a WebView in a mobile app.  Exporting to a PDF or Excel don't work properly. For now, I am modifying the source to inject code to communicate with my native app.

I see that you have an unused export option `saveToBinary`. It's currently empty. What would be great if there was a callback on the Export or Save, and it would simply pass me the uint8array and I can handle it myself.

**Comment by VeraDidenko** [comment]
Hello, @Clancey,

Thank you for your feedback.

Actually, there is a way to get the exported data as a `Uint8Array`.
This can be achieved using the following construction:

```
function excelToValue() {
  webdatarocks.exportTo("excel", null, (res) => {
    console.log(res);   // will contain data as a Uint8Array
  });
}
```
 
You are welcome to check out the following example: [https://codepen.io/webdatarocks/pen/GREqLvy](https://codepen.io/webdatarocks/pen/GREqLvy).
Also, a similar case was discussed in the following thread: [https://www.webdatarocks.com/question/how-to-get-report-table-html-content/](https://www.webdatarocks.com/question/how-to-get-report-table-html-content/).

We hope this helps!

Kind regards,
Vera
