### ISSUE TITLE
Support for weighted Average of two columns

### ISSUE THREAD

**Issue by bazooka720** [WebDataRocks/web-pivot-table#8]
Is there any support possible for weighted average score calculation? Is it possible?

**Comment by tanyagryshko** [comment]
Hello,

Thank you for your question. 

It is possible to calculate the weighted average with the help of calculated values in WebDataRocks. Here is a demo sample with the weighted average calculated through two calculated values: [https://codepen.io/webdatarocks/pen/qBjZRNB](https://codepen.io/webdatarocks/pen/qBjZRNB). 
For more info on calculated values, [visit our docs](https://www.webdatarocks.com/doc/slice-object/).

In addition, please consider using [StackOverflow](https://stackoverflow.com/questions/tagged/webdatarocks) for further questions.

Kind regards,
Tetiana Hryshko
