### ISSUE TITLE
Can't get highcharts instance inside webdatarocks object

### ISSUE THREAD

**Issue by brdzamasina** [WebDataRocks/web-pivot-table#9]

**Comment by se7enteenblue** [comment]
Hello,

Thank you for contacting us.

We want to ask you for some details about the issue:

1. Which framework do you use?
2. Please provide us with a corresponding code sample that would demonstrate the problem.

Waiting to hear from you.

Kind regards,
Nadia

**Comment by se7enteenblue** [comment]
Closed due to inactivity.
